### ISSUE TITLE
[NumberGuesser] Таймер

### ISSUE THREAD

**Issue by pavel-b-novikov** [DrobotAlena/nsudotnet#1]
Обоснуйте необходимость использования именно Stopwatch-таймера. Какие еще таймеры бывают в .NET?

**Comment by DrobotAlena** [comment]
Для измерения времени еще можно было воспользоваться структурой DateTime. 
Особой необходимости применения именно Stopwatch-таймера здесь действительно нет, т.к. измеряем секунды и минуты. Код с ним мне показался более интуитивно понятным, поэтому использовала его.

**Comment by pavel-b-novikov** [comment]
Ну а дальше? Какие еще таймеры-то бывают?

**Comment by DrobotAlena** [comment]
System.Windows.Forms.Timer, System.Timers.Timer и System.Threading.Timer

**Comment by pavel-b-novikov** [comment]
Я знаю. Чем они отличаются, зачем нужны?

**Comment by DrobotAlena** [comment]
Объекты Timer позволяют выполнять определенные действия через некоторый интервал времени.

Таймер System.Windows.Forms.Timer является  компонентом Windows Forms, который запускает событие и выполняет код в одном или нескольких обработчиков событий с регулярными интервалами. События таймера System.Windows.Forms.Timer вызываются в контексте UI Tread и экземпляры этого класса не потокобезопасны, он предназначен для использования в однопоточной среде. 

События таймера System.Timers.Timer вызываются в контексте UI Tread или Worker thread и экземпляры этого класса потокобезопасны: Этот таймер запускает событие и выполняет код в одном или нескольких обработчиках событий с регулярными интервалами. Класс предназначен для использования в качестве серверного или сервисного компонента в многопоточной среде.

События таймера System.Threading.Timer вызываются в контексте Worker thread и экземпляры этого класса потокобезопасны. Этот таймер выполняет один метод через регулярные интервалы. Метод выполняется в отдельном потоке пула потоков, предоставляемого системой. Метод определяется, когда таймер создается и не может быть изменен. Этот таймер предназначен для использования в качестве серверного или служебного компонента в многопоточной среде.

**Comment by pavel-b-novikov** [comment]
Я правильно понимаю что вы просто копипастите мне MSDN?

**Comment by DrobotAlena** [comment]
Уточняла информацию на других источниках, но самый полный ответ на ваш вопрос был на MSDN. Поэтому информацию взяла оттуда.

**Comment by pavel-b-novikov** [comment]
Послушайте, самый полный ответ на свой вопрос включая набитые граблями шишки от использования таймеров под нагрузкой и с утечками памяти я сам себе могу дать. 
Меня интересует что отложится у вас в голове.

**Comment by DrobotAlena** [comment]
В голове у меня отложилось, что для измерения времени в общем случае можно использовать структуру DateTime. Для более точных измерений можно использовать Stopwatch-таймер.
Что классы Timer позволяют выполнять какие-либо действия через определенные промежутки времени. Что есть три класса таймеров: System.Windows.Forms.Timer, System.Timers.Timer и System.Threading.Timer. Первый из них не предназначен для работы с несколькими потоками, остальные предназначены. Класс System.Threading.Timer позволяет выполнять только один метод через некоторые интервалы методы, и менять этот метод нельзя. К объекту класса System.Timers.Timer можно прикрепить несколько обработчиков, которые будут вызваны по истечению интервала времени.

**Comment by pavel-b-novikov** [comment]
Ну это не совсем так, но ладно. 
Простите, stopwatch у меня в голове всегда вызывает вопрос про таймеры в общем
