### ISSUE TITLE
[NumberGuesser] Обидный комментарий

### ISSUE THREAD

**Issue by pavel-b-novikov** [DrobotAlena/nsudotnet#2]
Обидно написано копированием кода. Разверните в метод

**Comment by DrobotAlena** [comment]
Не совсем поняла, нужно вынести в отдельный метод написание комментария пользователю или написание именно обидного комментария пользователю?

Вынесла в отдельный метод написание комментария пользователю, т.к. там было очень обидное копирование кода - менялась только одна строка...

**Comment by pavel-b-novikov** [comment]
Блин, а я забыл уже на что я агрился. 

Просто уберите вот этот дзен-код
```
if (step % 4 == 0)
{
    writeComment = true;
}
else
{
    writeComment = false;
}
```

**Comment by DrobotAlena** [comment]
убрала
