### ISSUE TITLE
[NumberGuesser] Папка Properties

### ISSUE THREAD

**Issue by pavel-b-novikov** [DrobotAlena/nsudotnet#3]
Вы её намеренно снесли из проекта вместе с AssemblyInfo? Кстати, а что делает AssemblyInfo? Как можно его использовать с пользой дела?

Верните Properties!!

**Comment by DrobotAlena** [comment]
У меня папка Properties не создавалась автоматически...

AssemblyInfo содержит атрибуты - сведения о сборке(название сборки, описание сборки, информацию о продукте, название компании, ...) 

У меня эти сведения были пустые, поэтому файл AssemblyInfo и папка Properties не создавались. Вернула папку и файл на место.
