### ISSUE TITLE
[JsonSerializer] Вложенные объекты

### ISSUE THREAD

**Issue by pavel-b-novikov** [DrobotAlena/nsudotnet#4]
А вложенные объекты оно не сериализует? О_о Это печально

**Comment by DrobotAlena** [comment]
Исправила

**Comment by pavel-b-novikov** [comment]
> outputFileWriter.WriteLine("not serializible");

Что, прям так и пишет? Получается невалидный JSON?

**Comment by DrobotAlena** [comment]
Исправила, теперь такие объекты не попадают в итоговый файл
