### ISSUE TITLE
[Enigma] Concat

### ISSUE THREAD

**Issue by pavel-b-novikov** [DrobotAlena/nsudotnet#5]
> String.Concat(directory,"/", inputFileNameWithoutExtension, ".key.txt")

Да не используйте вы блин Concat для этих целей!

**Comment by DrobotAlena** [comment]
Изменила способ получения имени файла

**Comment by pavel-b-novikov** [comment]
> String keyFileName = inputFile.Replace(".txt", ".key.txt");

Вы серьезно?

**Comment by DrobotAlena** [comment]
`String keyFileName = Path.Combine(directory, String.Format("{0}.key.txt", inputFileNameWithoutExtension));`

Так будет лучше? Изменила.

**Comment by pavel-b-novikov** [comment]
бинго
